import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { describe, expect, it } from "vitest";

/**
 * The old brand spelling must not come back.
 *
 * The app is Hikaya — حكاية, *hi-KAA-ya*. It was Hakiya, which spells حكية,
 * and before that Lahja. The rename to Hikaya was a find-and-replace over the
 * tree, and a find-and-replace is exactly the kind of change that looks
 * complete and is not: it got missed twice in one afternoon, both times
 * silently.
 *
 * Once because the replace matched `Hakiya` case-sensitively, which is right
 * for prose and wrong for two Playwright locators that matched their own
 * targets with `/back to hakiya/i` and `/join hakiya/i` — they went looking
 * for a word the button and heading no longer said. Once because the file
 * filter listed ts/tsx/html/json/webmanifest/md/css and so never opened a
 * `.js`, `.mjs` or `.svg` at all. That second gap hid a real bug: `sw.js`
 * falls back to a literal when a push arrives with no title of its own, and
 * that fallback is what an installed app writes into the notification tray,
 * so it would have said Hakiya under a Hikaya icon.
 *
 * Neither was caught by a test. Both were caught by someone reading a diff.
 * This is that reading, made mechanical: every occurrence of the old spelling
 * anywhere in the tree has to be one of the ones named below, or the suite
 * goes red with the file and line that reintroduced it.
 *
 * The allow-list is the point of the check, not an escape from it. Everything
 * on it is a string the old name is *correct* in — a live domain, a storage
 * key people already have — and each entry says why. A new entry is a claim
 * that a fifth such string exists, which is the kind of claim review should
 * see rather than a thing a rename should be able to do quietly.
 */

/** Files the scan opens: text the brand could plausibly be written into. */
const SCANNED = /\.(ts|tsx|js|mjs|html|css|svg|json|webmanifest|md|sql|yml|toml|txt)$/;

/**
 * `qa/output/` is a crawl's own record of a past run rather than source — it
 * is regenerated by re-crawling, never edited, and rewriting it by hand would
 * falsify the snapshot it exists to be.
 */
const SKIPPED_DIRS = ["qa/output/"];

/**
 * Where the old spelling is still the right answer.
 *
 * Each pattern is matched against the whole token the occurrence sits in, so
 * `hakiya.app` matches inside `hello@hakiya.app` and `ids.hakiya.app` without
 * needing an entry for each.
 */
const ALLOWED: ReadonlyArray<{ pattern: RegExp; reason: string }> = [
  {
    pattern: /hakiya\.app/i,
    reason:
      "The live domain, and everything hanging off it: the site itself, hello@, " +
      "the ids. subdomain reviewer logins map onto, and the CORS allow-list. " +
      "Moving it is DNS, Supabase auth and Stripe, not a code edit.",
  },
  {
    pattern: /^hakiya[_:]/i,
    reason:
      "localStorage keys. Everyone who has used the app already has these, and " +
      "renaming them without a second migration pass drops their settings on the " +
      "floor — see brandMigration.ts, which exists because that was true of the " +
      "lahja -> hakiya rename too.",
  },
  {
    pattern: /^hakiya-(?:shell|assets|audio|share-inbox|reminder|due)\b/i,
    reason:
      "Service worker cache names, and the tags that group push notifications " +
      "so a second one replaces the first rather than stacking. None are " +
      "displayed. hakiya-share-inbox in particular is agreed verbatim between " +
      "public/sw.js and src/lib/shareInbox.ts; moving one side alone orphans a " +
      "share the worker has already stashed.",
  },
  {
    pattern: /^hakiya-(?:lockup|logo|icon|mark)\b/i,
    reason: "Asset filenames in src/assets. Internal, never rendered as text.",
  },
  {
    pattern: /^hakiya(?:Lockup|Mark|Clip)$/,
    reason:
      "Import bindings and the Feed history-state key. Identifiers, not copy.",
  },
  {
    pattern: /^HakiyaStage$/,
    reason:
      "The Anki import stage type. Internal, and it already carries a deprecated " +
      "LahjaStage alias from the last rename — renaming it again buys nothing.",
  },
  {
    pattern: /^hakiya-good$/,
    reason: "An invite-code fixture value in e2e/auth.spec.ts. Arbitrary test data.",
  },
  {
    pattern: /^__hakiya_storage_probe__/,
    reason:
      "The key storageBootstrap writes and deletes to find out whether storage " +
      "throws. Never read back, never displayed, alive for two statements.",
  },
  {
    pattern: /^HAKIYA(?:[0-9]+|(?:-[A-Z0-9]+)+)?$/,
    reason:
      "The uppercase spelling, which is data rather than the brand. " +
      "parseLessonXlsx matches it in the header row of authored .xlsx files, so " +
      "dropping it stops importing every workbook written before the rename — " +
      "the same reason LAHJA is still listed beside it. The rest are arbitrary " +
      "invite-code fixtures in tests.",
  },
];

/**
 * Bare prose occurrences that are deliberate.
 *
 * Narrower than ALLOWED on purpose: this one names a file and the phrase, so
 * it cannot quietly cover a second occurrence that drifts into the same file.
 */
const ALLOWED_PHRASES: ReadonlyArray<{ file: string; phrase: string; reason: string }> = [
  {
    file: "src/lib/ankiImport/types.ts",
    phrase: "Lahja → Hakiya rename",
    reason:
      "A note about what happened, not a use of the name. That rename really did " +
      "go to Hakiya; spelling it Hikaya here would make the comment false.",
  },
  {
    file: "src/lib/brandMigration.ts",
    phrase: "`hakiya*`",
    reason:
      "The header naming the key namespace this module migrates lahja* into. " +
      "Those keys are still spelled hakiya* in every browser that has them, so " +
      "the comment is describing what is on disk, not what the app is called.",
  },
  {
    file: "src/lib/brandMigration.test.ts",
    phrase: "`hakiya*`",
    reason:
      "Same header, restated over the test that holds the migration to it. It " +
      "goes stale only if the keys themselves move, which is the change this " +
      "guard wants someone to notice rather than the one it wants to prevent.",
  },
];

/** The token an occurrence sits in — `hello@hakiya.app`, `hakiya_theme`, `HakiyaStage`. */
const TOKEN = /[A-Za-z0-9_.:@-]*hakiya[A-Za-z0-9_.:@-]*/gi;

/**
 * Punctuation the token grabbed from its surroundings rather than its own name.
 * `state?.hakiyaClip` and `{ hakiyaClip: id }` are the same identifier.
 */
const trim = (token: string): string => token.replace(/^[.:@-]+/, "").replace(/[.:@-]+$/, "");

/**
 * A token is allowed if either form matches, because trailing punctuation is
 * sometimes the name and sometimes the syntax around it: the `:` in
 * `"hakiya:"` is part of the storage-key prefix, the one in `{ hakiyaClip: x }`
 * is not, and nothing about the character says which.
 */
const isAllowed = (token: string): boolean =>
  ALLOWED.some((entry) => entry.pattern.test(token) || entry.pattern.test(trim(token)));

interface Violation {
  file: string;
  line: number;
  token: string;
  text: string;
}

function scannedFiles(): string[] {
  const tracked = execFileSync("git", ["ls-files", "-z"], {
    cwd: process.cwd(),
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  }).split("\0");

  return tracked.filter(
    (file) =>
      file.length > 0 &&
      SCANNED.test(file) &&
      !SKIPPED_DIRS.some((dir) => file.startsWith(dir)) &&
      !file.endsWith("src/test/brandSpelling.test.ts"),
  );
}

function violationsIn(file: string): Violation[] {
  let body: string;
  try {
    body = readFileSync(file, "utf8");
  } catch {
    return []; // unreadable or not really text — nothing to police
  }
  if (!/hakiya/i.test(body)) return [];

  const found: Violation[] = [];
  body.split("\n").forEach((text, index) => {
    const phrased = ALLOWED_PHRASES.some(
      (entry) => entry.file === file && text.includes(entry.phrase),
    );
    if (phrased) return;

    for (const match of text.matchAll(TOKEN)) {
      const token = match[0];
      if (isAllowed(token)) continue;
      found.push({ file, line: index + 1, token, text: text.trim().slice(0, 120) });
    }
  });
  return found;
}

describe("brand spelling", () => {
  it("has no unexplained use of the old name", () => {
    const violations = scannedFiles().flatMap(violationsIn);

    const report = violations
      .map((v) => `  ${v.file}:${v.line}  ${v.token}\n      ${v.text}`)
      .join("\n");

    expect(
      violations,
      violations.length === 0
        ? ""
        : `The app is spelled Hikaya. These carry the old spelling and are not on ` +
            `the allow-list in this file:\n\n${report}\n\n` +
            `Rename them, or — if the old name is genuinely correct there, as it is ` +
            `for the live domain and for storage keys people already have — add an ` +
            `entry with the reason why.`,
    ).toEqual([]);
  });

  it("scans the file types the rename pass missed", () => {
    // The rename skipped js, mjs and svg outright. A guard that inherits that
    // blind spot would have passed on the sw.js bug it exists to catch.
    const files = scannedFiles();
    for (const ext of ["js", "mjs", "svg", "ts", "tsx", "html", "md"]) {
      expect(
        files.some((file) => file.endsWith(`.${ext}`)),
        `no .${ext} file is being scanned`,
      ).toBe(true);
    }
    expect(files).toContain("public/sw.js");
    expect(files).toContain("src/assets/sadu-frame.svg");
  });

  it("would fail on the two misses that got through", () => {
    // The real regressions, as tokens: a case-insensitive locator's target and
    // sw.js's notification fallback. Neither may ever be quietly allowed.
    for (const token of ["hakiya", "Hakiya"]) {
      expect(
        ALLOWED.some((entry) => entry.pattern.test(token)),
        `a bare "${token}" is allowed by some pattern — the guard has a hole`,
      ).toBe(false);
    }
  });

  it("allows nothing it cannot justify", () => {
    for (const entry of [...ALLOWED, ...ALLOWED_PHRASES]) {
      expect(entry.reason.length).toBeGreaterThan(40);
    }
  });
});
