-- A picture of the mnemonic, alongside the mnemonic itself.
--
-- The text hook (`mnemonic`, added per-deck in 20260801103000 and its
-- siblings) is only half of the technique it implements: the keyword method
-- works because the learner *sees* the absurd scene, and a learner who cannot
-- picture it from prose gets none of the benefit. So each deck's row gets a
-- second column for the rendered scene, generated from that row's own
-- mnemonic and stored in the existing public `flashcard-images` bucket.
--
-- One column per deck rather than a shared table, for the same reason the
-- mnemonic itself lives here: the image is personal to the learner (it
-- illustrates *their* hook), and word_reviews is already where a curriculum
-- word's personal state goes — vocabulary_words is shared by everybody.

ALTER TABLE public.user_vocabulary
  ADD COLUMN IF NOT EXISTS mnemonic_image_url text;

ALTER TABLE public.user_phrases
  ADD COLUMN IF NOT EXISTS mnemonic_image_url text;

ALTER TABLE public.word_reviews
  ADD COLUMN IF NOT EXISTS mnemonic_image_url text;

COMMENT ON COLUMN public.user_vocabulary.mnemonic_image_url IS
  'Public URL of the illustrated mnemonic scene for this word, generated by the generate-mnemonic-image edge function.';
COMMENT ON COLUMN public.user_phrases.mnemonic_image_url IS
  'Public URL of the illustrated mnemonic scene for this phrase.';
COMMENT ON COLUMN public.word_reviews.mnemonic_image_url IS
  'Public URL of the illustrated mnemonic scene for this curriculum word, personal to the learner.';
