-- Schema for the authored curriculum tracks (curriculum/tracks/).
--
-- The tracks are compiled into a seed migration (20260905110000_seed_curriculum_tracks.sql,
-- generated by scripts/build-curriculum-seed.ts — never edited by hand). The
-- seed needs three things the lessons table did not have:
--
--   * a stable key to upsert on, so re-running a regenerated seed updates a
--     lesson in place instead of duplicating it and orphaning learner
--     progress. (stage_id, lesson_number) cannot be that key: the three
--     dialect tracks share stage and lesson numbers by design, and the
--     rebuild-only UNIQUE(stage_id, lesson_number) from 20260224000000 would
--     have rejected the second dialect outright. Production never had that
--     constraint, so dropping it changes nothing there.
--   * somewhere to keep the grammar notes, culture notes, dialogue and can-do
--     goals a track lesson carries beyond the spreadsheet importer's sections.
--     Same JSONB-array convention as lesson_sequence / real_world_prompts;
--     rendered by src/pages/Learn.tsx, empty for every lesson that predates
--     this.
--   * an example sentence per word. The tracks author one per word so the
--     word is never met as a bare list item — the design principle the
--     curriculum document calls its bedrock.

ALTER TABLE public.lessons
  ADD COLUMN IF NOT EXISTS source_key TEXT,
  ADD COLUMN IF NOT EXISTS can_do JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS grammar_notes JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS culture_notes JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS dialogue JSONB NOT NULL DEFAULT '[]'::jsonb;

CREATE UNIQUE INDEX IF NOT EXISTS lessons_source_key_key
  ON public.lessons (source_key);

ALTER TABLE public.lessons DROP CONSTRAINT IF EXISTS lessons_stage_id_lesson_number_key;

ALTER TABLE public.vocabulary_words
  ADD COLUMN IF NOT EXISTS example_arabic TEXT,
  ADD COLUMN IF NOT EXISTS example_transliteration TEXT,
  ADD COLUMN IF NOT EXISTS example_english TEXT;

COMMENT ON COLUMN public.lessons.source_key IS
  'curriculum/tracks lesson identity (<dialect>/s<stage>/l<nn>); NULL for lessons authored in the admin UI or imported from xlsx.';
