ALTER TABLE public.user_vocabulary
  ADD COLUMN IF NOT EXISTS mnemonic_image_url text;

ALTER TABLE public.user_phrases
  ADD COLUMN IF NOT EXISTS mnemonic_image_url text;

ALTER TABLE public.word_reviews
  ADD COLUMN IF NOT EXISTS mnemonic_image_url text;

COMMENT ON COLUMN public.user_vocabulary.mnemonic_image_url IS
  'Public URL of the illustrated mnemonic scene for this word, generated by the generate-mnemonic-image edge function.';
COMMENT ON COLUMN public.user_phrases.mnemonic_image_url IS
  'Public URL of the illustrated mnemonic scene for this phrase.';
COMMENT ON COLUMN public.word_reviews.mnemonic_image_url IS
  'Public URL of the illustrated mnemonic scene for this curriculum word, personal to the learner.';